### PR TITLE
Added README.md

### PR DESCRIPTION
**Pull request by 0n1cOn3**
Adding missing README and Prep Setup for the current project.

### CODE REVIEW

**Comment by yodaluca23** [comment]
MacOS?

**Comment by 0n1cOn3** [comment]
> MacOS?

Not tested. 
Atm only for Debian based systems

**Comment by tihmstar** [comment]
There are typos (in the link) and the project has been renamed since the PR so it also doesn't apply anymore.

Besides, i usually don't accept pull requests for READMEs

**Comment by 0n1cOn3** [comment]
This was also submitted 4 years ago. 
So ¯\_(ツ)_/¯ 

May I ask why?

**Comment by 0n1cOn3** [comment]
Keine Antwort is auch ne Antwort.
Sei es drum das Sie keine Readmes schreiben, aber es erleichtert die Handhabung um einiges. Und man muss nicht zuerst herausfinden, wie was wo. Desweiteren, ist das 4 Jahre her, in dem Sinne. Isch mir das sowas vo Wurscht. ¯\_(ツ)_/¯

**Pull request closed without merging**
